name: mock_http_overrides
description: MockHttpOverrides for tests
version: 0.0.1
homepage: https://github.com/cedvdb/mock_http_overrides

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test_screenshot: ^0.0.6
  file: ^7.0.1
  platform: ^3.1.6
